// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: game_engine.proto

package game_engine_pb

import (
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SingleRule_Operator int32

const (
	SingleRule_NO_OP SingleRule_Operator = 0
	SingleRule_EQ    SingleRule_Operator = 1
	SingleRule_NEQ   SingleRule_Operator = 2
	SingleRule_LT    SingleRule_Operator = 3
	SingleRule_LTE   SingleRule_Operator = 4
	SingleRule_GT    SingleRule_Operator = 5
	SingleRule_GTE   SingleRule_Operator = 6
)

// Enum value maps for SingleRule_Operator.
var (
	SingleRule_Operator_name = map[int32]string{
		0: "NO_OP",
		1: "EQ",
		2: "NEQ",
		3: "LT",
		4: "LTE",
		5: "GT",
		6: "GTE",
	}
	SingleRule_Operator_value = map[string]int32{
		"NO_OP": 0,
		"EQ":    1,
		"NEQ":   2,
		"LT":    3,
		"LTE":   4,
		"GT":    5,
		"GTE":   6,
	}
)

func (x SingleRule_Operator) Enum() *SingleRule_Operator {
	p := new(SingleRule_Operator)
	*p = x
	return p
}

func (x SingleRule_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SingleRule_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_game_engine_proto_enumTypes[0].Descriptor()
}

func (SingleRule_Operator) Type() protoreflect.EnumType {
	return &file_game_engine_proto_enumTypes[0]
}

func (x SingleRule_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SingleRule_Operator.Descriptor instead.
func (SingleRule_Operator) EnumDescriptor() ([]byte, []int) {
	return file_game_engine_proto_rawDescGZIP(), []int{2, 0}
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Effect *Effect `protobuf:"bytes,1,opt,name=effect,proto3" json:"effect,omitempty"`
	Rule   *Rule   `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	Error  *Error  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_engine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_game_engine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_game_engine_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetEffect() *Effect {
	if x != nil {
		return x.Effect
	}
	return nil
}

func (x *Action) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *Action) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Rule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to RuleField:
	//	*Rule_Single
	//	*Rule_And
	//	*Rule_Or
	RuleField isRule_RuleField `protobuf_oneof:"rule_field"`
}

func (x *Rule) Reset() {
	*x = Rule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_engine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_game_engine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_game_engine_proto_rawDescGZIP(), []int{1}
}

func (m *Rule) GetRuleField() isRule_RuleField {
	if m != nil {
		return m.RuleField
	}
	return nil
}

func (x *Rule) GetSingle() *SingleRule {
	if x, ok := x.GetRuleField().(*Rule_Single); ok {
		return x.Single
	}
	return nil
}

func (x *Rule) GetAnd() *AndRules {
	if x, ok := x.GetRuleField().(*Rule_And); ok {
		return x.And
	}
	return nil
}

func (x *Rule) GetOr() *OrRules {
	if x, ok := x.GetRuleField().(*Rule_Or); ok {
		return x.Or
	}
	return nil
}

type isRule_RuleField interface {
	isRule_RuleField()
}

type Rule_Single struct {
	Single *SingleRule `protobuf:"bytes,1,opt,name=single,proto3,oneof"`
}

type Rule_And struct {
	And *AndRules `protobuf:"bytes,2,opt,name=and,proto3,oneof"`
}

type Rule_Or struct {
	Or *OrRules `protobuf:"bytes,3,opt,name=or,proto3,oneof"`
}

func (*Rule_Single) isRule_RuleField() {}

func (*Rule_And) isRule_RuleField() {}

func (*Rule_Or) isRule_RuleField() {}

type SingleRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator SingleRule_Operator `protobuf:"varint,1,opt,name=operator,proto3,enum=game_engine.SingleRule_Operator" json:"operator,omitempty"`
	Left     *SingleRule_Operand `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right    *SingleRule_Operand `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
}

func (x *SingleRule) Reset() {
	*x = SingleRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_engine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleRule) ProtoMessage() {}

func (x *SingleRule) ProtoReflect() protoreflect.Message {
	mi := &file_game_engine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleRule.ProtoReflect.Descriptor instead.
func (*SingleRule) Descriptor() ([]byte, []int) {
	return file_game_engine_proto_rawDescGZIP(), []int{2}
}

func (x *SingleRule) GetOperator() SingleRule_Operator {
	if x != nil {
		return x.Operator
	}
	return SingleRule_NO_OP
}

func (x *SingleRule) GetLeft() *SingleRule_Operand {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *SingleRule) GetRight() *SingleRule_Operand {
	if x != nil {
		return x.Right
	}
	return nil
}

type AndRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rules []*Rule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
}

func (x *AndRules) Reset() {
	*x = AndRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_engine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AndRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndRules) ProtoMessage() {}

func (x *AndRules) ProtoReflect() protoreflect.Message {
	mi := &file_game_engine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndRules.ProtoReflect.Descriptor instead.
func (*AndRules) Descriptor() ([]byte, []int) {
	return file_game_engine_proto_rawDescGZIP(), []int{3}
}

func (x *AndRules) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type OrRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rules []*Rule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
}

func (x *OrRules) Reset() {
	*x = OrRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_engine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrRules) ProtoMessage() {}

func (x *OrRules) ProtoReflect() protoreflect.Message {
	mi := &file_game_engine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrRules.ProtoReflect.Descriptor instead.
func (*OrRules) Descriptor() ([]byte, []int) {
	return file_game_engine_proto_rawDescGZIP(), []int{4}
}

func (x *OrRules) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type Effect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operation:
	//	*Effect_Update_
	Operation isEffect_Operation `protobuf_oneof:"operation"`
}

func (x *Effect) Reset() {
	*x = Effect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_engine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_game_engine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect.ProtoReflect.Descriptor instead.
func (*Effect) Descriptor() ([]byte, []int) {
	return file_game_engine_proto_rawDescGZIP(), []int{5}
}

func (m *Effect) GetOperation() isEffect_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (x *Effect) GetUpdate() *Effect_Update {
	if x, ok := x.GetOperation().(*Effect_Update_); ok {
		return x.Update
	}
	return nil
}

type isEffect_Operation interface {
	isEffect_Operation()
}

type Effect_Update_ struct {
	Update *Effect_Update `protobuf:"bytes,1,opt,name=update,proto3,oneof"`
}

func (*Effect_Update_) isEffect_Operation() {}

type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_engine_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_game_engine_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_game_engine_proto_rawDescGZIP(), []int{6}
}

func (x *Field) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*Value_BoolValue
	//	*Value_IntegerValue
	//	*Value_FloatValue
	//	*Value_StringValue
	Value isValue_Value `protobuf_oneof:"value"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_engine_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_game_engine_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_game_engine_proto_rawDescGZIP(), []int{7}
}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Value) GetBoolValue() bool {
	if x, ok := x.GetValue().(*Value_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *Value) GetIntegerValue() int64 {
	if x, ok := x.GetValue().(*Value_IntegerValue); ok {
		return x.IntegerValue
	}
	return 0
}

func (x *Value) GetFloatValue() float32 {
	if x, ok := x.GetValue().(*Value_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (x *Value) GetStringValue() string {
	if x, ok := x.GetValue().(*Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

type isValue_Value interface {
	isValue_Value()
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_IntegerValue struct {
	IntegerValue int64 `protobuf:"varint,2,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type Value_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,3,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*Value_BoolValue) isValue_Value() {}

func (*Value_IntegerValue) isValue_Value() {}

func (*Value_FloatValue) isValue_Value() {}

func (*Value_StringValue) isValue_Value() {}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code    string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg     string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_engine_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_game_engine_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_game_engine_proto_rawDescGZIP(), []int{8}
}

func (x *Error) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SingleRule_Operand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Contents:
	//	*SingleRule_Operand_Field
	//	*SingleRule_Operand_Value
	Contents isSingleRule_Operand_Contents `protobuf_oneof:"contents"`
}

func (x *SingleRule_Operand) Reset() {
	*x = SingleRule_Operand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_engine_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleRule_Operand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleRule_Operand) ProtoMessage() {}

func (x *SingleRule_Operand) ProtoReflect() protoreflect.Message {
	mi := &file_game_engine_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleRule_Operand.ProtoReflect.Descriptor instead.
func (*SingleRule_Operand) Descriptor() ([]byte, []int) {
	return file_game_engine_proto_rawDescGZIP(), []int{2, 0}
}

func (m *SingleRule_Operand) GetContents() isSingleRule_Operand_Contents {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (x *SingleRule_Operand) GetField() *Field {
	if x, ok := x.GetContents().(*SingleRule_Operand_Field); ok {
		return x.Field
	}
	return nil
}

func (x *SingleRule_Operand) GetValue() *Value {
	if x, ok := x.GetContents().(*SingleRule_Operand_Value); ok {
		return x.Value
	}
	return nil
}

type isSingleRule_Operand_Contents interface {
	isSingleRule_Operand_Contents()
}

type SingleRule_Operand_Field struct {
	Field *Field `protobuf:"bytes,1,opt,name=field,proto3,oneof"`
}

type SingleRule_Operand_Value struct {
	Value *Value `protobuf:"bytes,2,opt,name=value,proto3,oneof"`
}

func (*SingleRule_Operand_Field) isSingleRule_Operand_Contents() {}

func (*SingleRule_Operand_Value) isSingleRule_Operand_Contents() {}

type Effect_Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dest *Field `protobuf:"bytes,1,opt,name=dest,proto3" json:"dest,omitempty"`
	// Types that are assignable to Src:
	//	*Effect_Update_SrcField
	//	*Effect_Update_SrcValue
	Src isEffect_Update_Src `protobuf_oneof:"src"`
}

func (x *Effect_Update) Reset() {
	*x = Effect_Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_engine_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Effect_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_Update) ProtoMessage() {}

func (x *Effect_Update) ProtoReflect() protoreflect.Message {
	mi := &file_game_engine_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect_Update.ProtoReflect.Descriptor instead.
func (*Effect_Update) Descriptor() ([]byte, []int) {
	return file_game_engine_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Effect_Update) GetDest() *Field {
	if x != nil {
		return x.Dest
	}
	return nil
}

func (m *Effect_Update) GetSrc() isEffect_Update_Src {
	if m != nil {
		return m.Src
	}
	return nil
}

func (x *Effect_Update) GetSrcField() *Field {
	if x, ok := x.GetSrc().(*Effect_Update_SrcField); ok {
		return x.SrcField
	}
	return nil
}

func (x *Effect_Update) GetSrcValue() *Value {
	if x, ok := x.GetSrc().(*Effect_Update_SrcValue); ok {
		return x.SrcValue
	}
	return nil
}

type isEffect_Update_Src interface {
	isEffect_Update_Src()
}

type Effect_Update_SrcField struct {
	SrcField *Field `protobuf:"bytes,2,opt,name=src_field,json=srcField,proto3,oneof"`
}

type Effect_Update_SrcValue struct {
	SrcValue *Value `protobuf:"bytes,3,opt,name=src_value,json=srcValue,proto3,oneof"`
}

func (*Effect_Update_SrcField) isEffect_Update_Src() {}

func (*Effect_Update_SrcValue) isEffect_Update_Src() {}

var file_game_engine_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "game_engine.is_action_service",
		Tag:           "varint,50000,opt,name=is_action_service",
		Filename:      "game_engine.proto",
	},
	{
		ExtendedType:  (*descriptor.MethodOptions)(nil),
		ExtensionType: (*Action)(nil),
		Field:         50001,
		Name:          "game_engine.action",
		Tag:           "bytes,50001,opt,name=action",
		Filename:      "game_engine.proto",
	},
	{
		ExtendedType:  (*descriptor.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "game_engine.is_game_state",
		Tag:           "varint,50002,opt,name=is_game_state",
		Filename:      "game_engine.proto",
	},
}

// Extension fields to descriptor.ServiceOptions.
var (
	// optional bool is_action_service = 50000;
	E_IsActionService = &file_game_engine_proto_extTypes[0] // TODO: deliberate these numbers
)

// Extension fields to descriptor.MethodOptions.
var (
	// optional game_engine.Action action = 50001;
	E_Action = &file_game_engine_proto_extTypes[1] // TODO: deliberate these numbers
)

// Extension fields to descriptor.MessageOptions.
var (
	// optional bool is_game_state = 50002;
	E_IsGameState = &file_game_engine_proto_extTypes[2]
)

var File_game_engine_proto protoreflect.FileDescriptor

var file_game_engine_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x86, 0x01, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a,
	0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x45, 0x66, 0x66, 0x65,
	0x63, 0x74, 0x52, 0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x72, 0x75,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x75, 0x6c,
	0x65, 0x12, 0x28, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x9a, 0x01, 0x0a, 0x04,
	0x52, 0x75, 0x6c, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x48, 0x00, 0x52,
	0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x03, 0x61, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x2e, 0x41, 0x6e, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x03, 0x61,
	0x6e, 0x64, 0x12, 0x26, 0x0a, 0x02, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x72, 0x52,
	0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x72, 0x42, 0x0c, 0x0a, 0x0a, 0x72, 0x75,
	0x6c, 0x65, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0xef, 0x02, 0x0a, 0x0a, 0x53, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x3c, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x75,
	0x6c, 0x65, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x33, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x6e, 0x64, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x35, 0x0a, 0x05, 0x72, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x75,
	0x6c, 0x65, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68,
	0x74, 0x1a, 0x6d, 0x0a, 0x07, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x2a, 0x0a, 0x05,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x48,
	0x00, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0x48, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x09, 0x0a, 0x05,
	0x4e, 0x4f, 0x5f, 0x4f, 0x50, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x45, 0x51, 0x10, 0x01, 0x12,
	0x07, 0x0a, 0x03, 0x4e, 0x45, 0x51, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x4c, 0x54, 0x10, 0x03,
	0x12, 0x07, 0x0a, 0x03, 0x4c, 0x54, 0x45, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02, 0x47, 0x54, 0x10,
	0x05, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x54, 0x45, 0x10, 0x06, 0x22, 0x33, 0x0a, 0x08, 0x41, 0x6e,
	0x64, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x22,
	0x32, 0x0a, 0x07, 0x4f, 0x72, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x72, 0x75,
	0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75,
	0x6c, 0x65, 0x73, 0x22, 0xeb, 0x01, 0x0a, 0x06, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x12, 0x34,
	0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x45, 0x66, 0x66,
	0x65, 0x63, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x1a, 0x9d, 0x01, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x26, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x09, 0x73, 0x72, 0x63, 0x5f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x48, 0x00,
	0x52, 0x08, 0x73, 0x72, 0x63, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x31, 0x0a, 0x09, 0x73, 0x72,
	0x63, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x48, 0x00, 0x52, 0x08, 0x73, 0x72, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x05, 0x0a,
	0x03, 0x73, 0x72, 0x63, 0x42, 0x0b, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x1b, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xa0,
	0x01, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09,
	0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x25, 0x0a, 0x0d, 0x69, 0x6e, 0x74,
	0x65, 0x67, 0x65, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x00, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x21, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x47, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x3a, 0x50, 0x0a, 0x11, 0x69, 0x73,
	0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0xd0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x88, 0x01, 0x01, 0x3a, 0x50, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x3a, 0x48,
	0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0xd2, 0x86, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01, 0x42, 0x40, 0x5a, 0x3e, 0x61, 0x6e, 0x67, 0x65,
	0x6c, 0x62, 0x65, 0x6c, 0x74, 0x72, 0x61, 0x6e, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x65, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d,
	0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_game_engine_proto_rawDescOnce sync.Once
	file_game_engine_proto_rawDescData = file_game_engine_proto_rawDesc
)

func file_game_engine_proto_rawDescGZIP() []byte {
	file_game_engine_proto_rawDescOnce.Do(func() {
		file_game_engine_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_engine_proto_rawDescData)
	})
	return file_game_engine_proto_rawDescData
}

var file_game_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_game_engine_proto_goTypes = []interface{}{
	(SingleRule_Operator)(0),          // 0: game_engine.SingleRule.Operator
	(*Action)(nil),                    // 1: game_engine.Action
	(*Rule)(nil),                      // 2: game_engine.Rule
	(*SingleRule)(nil),                // 3: game_engine.SingleRule
	(*AndRules)(nil),                  // 4: game_engine.AndRules
	(*OrRules)(nil),                   // 5: game_engine.OrRules
	(*Effect)(nil),                    // 6: game_engine.Effect
	(*Field)(nil),                     // 7: game_engine.Field
	(*Value)(nil),                     // 8: game_engine.Value
	(*Error)(nil),                     // 9: game_engine.Error
	(*SingleRule_Operand)(nil),        // 10: game_engine.SingleRule.Operand
	(*Effect_Update)(nil),             // 11: game_engine.Effect.Update
	(*descriptor.ServiceOptions)(nil), // 12: google.protobuf.ServiceOptions
	(*descriptor.MethodOptions)(nil),  // 13: google.protobuf.MethodOptions
	(*descriptor.MessageOptions)(nil), // 14: google.protobuf.MessageOptions
}
var file_game_engine_proto_depIdxs = []int32{
	6,  // 0: game_engine.Action.effect:type_name -> game_engine.Effect
	2,  // 1: game_engine.Action.rule:type_name -> game_engine.Rule
	9,  // 2: game_engine.Action.error:type_name -> game_engine.Error
	3,  // 3: game_engine.Rule.single:type_name -> game_engine.SingleRule
	4,  // 4: game_engine.Rule.and:type_name -> game_engine.AndRules
	5,  // 5: game_engine.Rule.or:type_name -> game_engine.OrRules
	0,  // 6: game_engine.SingleRule.operator:type_name -> game_engine.SingleRule.Operator
	10, // 7: game_engine.SingleRule.left:type_name -> game_engine.SingleRule.Operand
	10, // 8: game_engine.SingleRule.right:type_name -> game_engine.SingleRule.Operand
	2,  // 9: game_engine.AndRules.rules:type_name -> game_engine.Rule
	2,  // 10: game_engine.OrRules.rules:type_name -> game_engine.Rule
	11, // 11: game_engine.Effect.update:type_name -> game_engine.Effect.Update
	7,  // 12: game_engine.SingleRule.Operand.field:type_name -> game_engine.Field
	8,  // 13: game_engine.SingleRule.Operand.value:type_name -> game_engine.Value
	7,  // 14: game_engine.Effect.Update.dest:type_name -> game_engine.Field
	7,  // 15: game_engine.Effect.Update.src_field:type_name -> game_engine.Field
	8,  // 16: game_engine.Effect.Update.src_value:type_name -> game_engine.Value
	12, // 17: game_engine.is_action_service:extendee -> google.protobuf.ServiceOptions
	13, // 18: game_engine.action:extendee -> google.protobuf.MethodOptions
	14, // 19: game_engine.is_game_state:extendee -> google.protobuf.MessageOptions
	1,  // 20: game_engine.action:type_name -> game_engine.Action
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	20, // [20:21] is the sub-list for extension type_name
	17, // [17:20] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_game_engine_proto_init() }
func file_game_engine_proto_init() {
	if File_game_engine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_engine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_engine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_engine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_engine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AndRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_engine_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_engine_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Effect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_engine_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_engine_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_engine_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_engine_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleRule_Operand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_engine_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Effect_Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_game_engine_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Rule_Single)(nil),
		(*Rule_And)(nil),
		(*Rule_Or)(nil),
	}
	file_game_engine_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Effect_Update_)(nil),
	}
	file_game_engine_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Value_BoolValue)(nil),
		(*Value_IntegerValue)(nil),
		(*Value_FloatValue)(nil),
		(*Value_StringValue)(nil),
	}
	file_game_engine_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*SingleRule_Operand_Field)(nil),
		(*SingleRule_Operand_Value)(nil),
	}
	file_game_engine_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*Effect_Update_SrcField)(nil),
		(*Effect_Update_SrcValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_engine_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_game_engine_proto_goTypes,
		DependencyIndexes: file_game_engine_proto_depIdxs,
		EnumInfos:         file_game_engine_proto_enumTypes,
		MessageInfos:      file_game_engine_proto_msgTypes,
		ExtensionInfos:    file_game_engine_proto_extTypes,
	}.Build()
	File_game_engine_proto = out.File
	file_game_engine_proto_rawDesc = nil
	file_game_engine_proto_goTypes = nil
	file_game_engine_proto_depIdxs = nil
}
