// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: github.com/angelbeltran/game-engine/examples/puerto-rico/cargo_ship.proto

package puerto_rico_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CargoShipID int32

const (
	CargoShipID_NO_SHIP      CargoShipID = 0
	CargoShipID_WHARF_SHIP   CargoShipID = 1
	CargoShipID_SHIP_4_SLOTS CargoShipID = 4
	CargoShipID_SHIP_5_SLOTS CargoShipID = 5
	CargoShipID_SHIP_6_SLOTS CargoShipID = 6
	CargoShipID_SHIP_7_SLOTS CargoShipID = 7
	CargoShipID_SHIP_8_SLOTS CargoShipID = 8
)

// Enum value maps for CargoShipID.
var (
	CargoShipID_name = map[int32]string{
		0: "NO_SHIP",
		1: "WHARF_SHIP",
		4: "SHIP_4_SLOTS",
		5: "SHIP_5_SLOTS",
		6: "SHIP_6_SLOTS",
		7: "SHIP_7_SLOTS",
		8: "SHIP_8_SLOTS",
	}
	CargoShipID_value = map[string]int32{
		"NO_SHIP":      0,
		"WHARF_SHIP":   1,
		"SHIP_4_SLOTS": 4,
		"SHIP_5_SLOTS": 5,
		"SHIP_6_SLOTS": 6,
		"SHIP_7_SLOTS": 7,
		"SHIP_8_SLOTS": 8,
	}
)

func (x CargoShipID) Enum() *CargoShipID {
	p := new(CargoShipID)
	*p = x
	return p
}

func (x CargoShipID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CargoShipID) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_enumTypes[0].Descriptor()
}

func (CargoShipID) Type() protoreflect.EnumType {
	return &file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_enumTypes[0]
}

func (x CargoShipID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CargoShipID.Descriptor instead.
func (CargoShipID) EnumDescriptor() ([]byte, []int) {
	return file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_rawDescGZIP(), []int{0}
}

type CargoShip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Good     GoodID `protobuf:"varint,1,opt,name=good,proto3,enum=puerto_rico_game.GoodID" json:"good,omitempty"`
	Quantity uint32 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *CargoShip) Reset() {
	*x = CargoShip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CargoShip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargoShip) ProtoMessage() {}

func (x *CargoShip) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargoShip.ProtoReflect.Descriptor instead.
func (*CargoShip) Descriptor() ([]byte, []int) {
	return file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_rawDescGZIP(), []int{0}
}

func (x *CargoShip) GetGood() GoodID {
	if x != nil {
		return x.Good
	}
	return GoodID_NO_GOOD
}

func (x *CargoShip) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto protoreflect.FileDescriptor

var file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_rawDesc = []byte{
	0x0a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x67,
	0x65, 0x6c, 0x62, 0x65, 0x6c, 0x74, 0x72, 0x61, 0x6e, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x65,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x70,
	0x75, 0x65, 0x72, 0x74, 0x6f, 0x2d, 0x72, 0x69, 0x63, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x67, 0x6f,
	0x5f, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x75, 0x65,
	0x72, 0x74, 0x6f, 0x5f, 0x72, 0x69, 0x63, 0x6f, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x1a, 0x43, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x67, 0x65, 0x6c, 0x62,
	0x65, 0x6c, 0x74, 0x72, 0x61, 0x6e, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x75, 0x65, 0x72,
	0x74, 0x6f, 0x2d, 0x72, 0x69, 0x63, 0x6f, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x55, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x53, 0x68, 0x69, 0x70, 0x12,
	0x2c, 0x0a, 0x04, 0x67, 0x6f, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e,
	0x70, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x5f, 0x72, 0x69, 0x63, 0x6f, 0x5f, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x49, 0x44, 0x52, 0x04, 0x67, 0x6f, 0x6f, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2a, 0x84, 0x01, 0x0a, 0x0b, 0x43, 0x61,
	0x72, 0x67, 0x6f, 0x53, 0x68, 0x69, 0x70, 0x49, 0x44, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x4f, 0x5f,
	0x53, 0x48, 0x49, 0x50, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x48, 0x41, 0x52, 0x46, 0x5f,
	0x53, 0x48, 0x49, 0x50, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x34,
	0x5f, 0x53, 0x4c, 0x4f, 0x54, 0x53, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x48, 0x49, 0x50,
	0x5f, 0x35, 0x5f, 0x53, 0x4c, 0x4f, 0x54, 0x53, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x48,
	0x49, 0x50, 0x5f, 0x36, 0x5f, 0x53, 0x4c, 0x4f, 0x54, 0x53, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c,
	0x53, 0x48, 0x49, 0x50, 0x5f, 0x37, 0x5f, 0x53, 0x4c, 0x4f, 0x54, 0x53, 0x10, 0x07, 0x12, 0x10,
	0x0a, 0x0c, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x38, 0x5f, 0x53, 0x4c, 0x4f, 0x54, 0x53, 0x10, 0x08,
	0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x6e, 0x67, 0x65, 0x6c, 0x62, 0x65, 0x6c, 0x74, 0x72, 0x61, 0x6e, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73,
	0x2f, 0x70, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x2d, 0x72, 0x69, 0x63, 0x6f, 0x2f, 0x70, 0x75, 0x65,
	0x72, 0x74, 0x6f, 0x5f, 0x72, 0x69, 0x63, 0x6f, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_rawDescOnce sync.Once
	file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_rawDescData = file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_rawDesc
)

func file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_rawDescGZIP() []byte {
	file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_rawDescOnce.Do(func() {
		file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_rawDescData)
	})
	return file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_rawDescData
}

var file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_goTypes = []interface{}{
	(CargoShipID)(0),  // 0: puerto_rico_game.CargoShipID
	(*CargoShip)(nil), // 1: puerto_rico_game.CargoShip
	(GoodID)(0),       // 2: puerto_rico_game.GoodID
}
var file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_depIdxs = []int32{
	2, // 0: puerto_rico_game.CargoShip.good:type_name -> puerto_rico_game.GoodID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_init() }
func file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_init() {
	if File_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto != nil {
		return
	}
	file_github_com_angelbeltran_game_engine_examples_puerto_rico_good_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CargoShip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_goTypes,
		DependencyIndexes: file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_depIdxs,
		EnumInfos:         file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_enumTypes,
		MessageInfos:      file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_msgTypes,
	}.Build()
	File_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto = out.File
	file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_rawDesc = nil
	file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_goTypes = nil
	file_github_com_angelbeltran_game_engine_examples_puerto_rico_cargo_ship_proto_depIdxs = nil
}
