// Generated by protoc-gen-game/generation. DO NOT EDIT.
package validation

type Type string

const (
	TypeNone Type = ""
	TypeBool Type = "bool"
	TypeInt Type = "int"
	TypeFloat Type = "float"
	TypeString Type = "string"
)
