// Generated by protoc-gen-game/generation. DO NOT EDIT.
package template

import (
	"github.com/jhump/protoreflect/desc"

	pb "github.com/angelbeltran/game-engine/protoc-gen-game/game_engine_pb"
)


//
// ----- Simple State Or Input References -----
//

type ReferenceParams struct {
	Reference *pb.Reference
	Variable string
}

func NewReferenceParams(variable string, reference *pb.Reference) ReferenceParams {
	return ReferenceParams{
		Variable: variable,
		Reference: reference,
	}
}

//
// ----- Values -----
//

type ValueParams struct {
	Value *pb.Value
	InputVariable string
	StateVariable string
}

func NewValueParams(value *pb.Value, input, state string) ValueParams {
	return ValueParams{
		Value: value,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolValueParams struct {
	Value *pb.BoolValue
	InputVariable string
	StateVariable string
}

func NewBoolValueParams(value *pb.BoolValue, input, state string) BoolValueParams {
	return BoolValueParams{
		Value: value,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntValueParams struct {
	Value *pb.IntValue
	InputVariable string
	StateVariable string
}

func NewIntValueParams(value *pb.IntValue, input, state string) IntValueParams {
	return IntValueParams{
		Value: value,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatValueParams struct {
	Value *pb.FloatValue
	InputVariable string
	StateVariable string
}

func NewFloatValueParams(value *pb.FloatValue, input, state string) FloatValueParams {
	return FloatValueParams{
		Value: value,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringValueParams struct {
	Value *pb.StringValue
	InputVariable string
	StateVariable string
}

func NewStringValueParams(value *pb.StringValue, input, state string) StringValueParams {
	return StringValueParams{
		Value: value,
		InputVariable: input,
		StateVariable: state,
	}
}


//
// ----- Unary Functions -----
//

type BoolToBoolFunctionParams struct {
	Function *pb.BoolToBoolFunction
	InputVariable string
	StateVariable string
}

func NewBoolToBoolFunctionParams(function *pb.BoolToBoolFunction, input, state string) BoolToBoolFunctionParams {
	return BoolToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolToIntFunctionParams struct {
	Function *pb.BoolToIntFunction
	InputVariable string
	StateVariable string
}

func NewBoolToIntFunctionParams(function *pb.BoolToIntFunction, input, state string) BoolToIntFunctionParams {
	return BoolToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolToFloatFunctionParams struct {
	Function *pb.BoolToFloatFunction
	InputVariable string
	StateVariable string
}

func NewBoolToFloatFunctionParams(function *pb.BoolToFloatFunction, input, state string) BoolToFloatFunctionParams {
	return BoolToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolToStringFunctionParams struct {
	Function *pb.BoolToStringFunction
	InputVariable string
	StateVariable string
}

func NewBoolToStringFunctionParams(function *pb.BoolToStringFunction, input, state string) BoolToStringFunctionParams {
	return BoolToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntToBoolFunctionParams struct {
	Function *pb.IntToBoolFunction
	InputVariable string
	StateVariable string
}

func NewIntToBoolFunctionParams(function *pb.IntToBoolFunction, input, state string) IntToBoolFunctionParams {
	return IntToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntToIntFunctionParams struct {
	Function *pb.IntToIntFunction
	InputVariable string
	StateVariable string
}

func NewIntToIntFunctionParams(function *pb.IntToIntFunction, input, state string) IntToIntFunctionParams {
	return IntToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntToFloatFunctionParams struct {
	Function *pb.IntToFloatFunction
	InputVariable string
	StateVariable string
}

func NewIntToFloatFunctionParams(function *pb.IntToFloatFunction, input, state string) IntToFloatFunctionParams {
	return IntToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntToStringFunctionParams struct {
	Function *pb.IntToStringFunction
	InputVariable string
	StateVariable string
}

func NewIntToStringFunctionParams(function *pb.IntToStringFunction, input, state string) IntToStringFunctionParams {
	return IntToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatToBoolFunctionParams struct {
	Function *pb.FloatToBoolFunction
	InputVariable string
	StateVariable string
}

func NewFloatToBoolFunctionParams(function *pb.FloatToBoolFunction, input, state string) FloatToBoolFunctionParams {
	return FloatToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatToIntFunctionParams struct {
	Function *pb.FloatToIntFunction
	InputVariable string
	StateVariable string
}

func NewFloatToIntFunctionParams(function *pb.FloatToIntFunction, input, state string) FloatToIntFunctionParams {
	return FloatToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatToFloatFunctionParams struct {
	Function *pb.FloatToFloatFunction
	InputVariable string
	StateVariable string
}

func NewFloatToFloatFunctionParams(function *pb.FloatToFloatFunction, input, state string) FloatToFloatFunctionParams {
	return FloatToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatToStringFunctionParams struct {
	Function *pb.FloatToStringFunction
	InputVariable string
	StateVariable string
}

func NewFloatToStringFunctionParams(function *pb.FloatToStringFunction, input, state string) FloatToStringFunctionParams {
	return FloatToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringToBoolFunctionParams struct {
	Function *pb.StringToBoolFunction
	InputVariable string
	StateVariable string
}

func NewStringToBoolFunctionParams(function *pb.StringToBoolFunction, input, state string) StringToBoolFunctionParams {
	return StringToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringToIntFunctionParams struct {
	Function *pb.StringToIntFunction
	InputVariable string
	StateVariable string
}

func NewStringToIntFunctionParams(function *pb.StringToIntFunction, input, state string) StringToIntFunctionParams {
	return StringToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringToFloatFunctionParams struct {
	Function *pb.StringToFloatFunction
	InputVariable string
	StateVariable string
}

func NewStringToFloatFunctionParams(function *pb.StringToFloatFunction, input, state string) StringToFloatFunctionParams {
	return StringToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringToStringFunctionParams struct {
	Function *pb.StringToStringFunction
	InputVariable string
	StateVariable string
}

func NewStringToStringFunctionParams(function *pb.StringToStringFunction, input, state string) StringToStringFunctionParams {
	return StringToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

//
// ----- Binary Functions -----
//

type BoolAndBoolToBoolFunctionParams struct {
	Function *pb.BoolAndBoolToBoolFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndBoolToBoolFunctionParams(function *pb.BoolAndBoolToBoolFunction, input, state string) BoolAndBoolToBoolFunctionParams {
	return BoolAndBoolToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolAndBoolToIntFunctionParams struct {
	Function *pb.BoolAndBoolToIntFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndBoolToIntFunctionParams(function *pb.BoolAndBoolToIntFunction, input, state string) BoolAndBoolToIntFunctionParams {
	return BoolAndBoolToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolAndBoolToFloatFunctionParams struct {
	Function *pb.BoolAndBoolToFloatFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndBoolToFloatFunctionParams(function *pb.BoolAndBoolToFloatFunction, input, state string) BoolAndBoolToFloatFunctionParams {
	return BoolAndBoolToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolAndBoolToStringFunctionParams struct {
	Function *pb.BoolAndBoolToStringFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndBoolToStringFunctionParams(function *pb.BoolAndBoolToStringFunction, input, state string) BoolAndBoolToStringFunctionParams {
	return BoolAndBoolToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolAndIntToBoolFunctionParams struct {
	Function *pb.BoolAndIntToBoolFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndIntToBoolFunctionParams(function *pb.BoolAndIntToBoolFunction, input, state string) BoolAndIntToBoolFunctionParams {
	return BoolAndIntToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolAndIntToIntFunctionParams struct {
	Function *pb.BoolAndIntToIntFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndIntToIntFunctionParams(function *pb.BoolAndIntToIntFunction, input, state string) BoolAndIntToIntFunctionParams {
	return BoolAndIntToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolAndIntToFloatFunctionParams struct {
	Function *pb.BoolAndIntToFloatFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndIntToFloatFunctionParams(function *pb.BoolAndIntToFloatFunction, input, state string) BoolAndIntToFloatFunctionParams {
	return BoolAndIntToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolAndIntToStringFunctionParams struct {
	Function *pb.BoolAndIntToStringFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndIntToStringFunctionParams(function *pb.BoolAndIntToStringFunction, input, state string) BoolAndIntToStringFunctionParams {
	return BoolAndIntToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolAndFloatToBoolFunctionParams struct {
	Function *pb.BoolAndFloatToBoolFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndFloatToBoolFunctionParams(function *pb.BoolAndFloatToBoolFunction, input, state string) BoolAndFloatToBoolFunctionParams {
	return BoolAndFloatToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolAndFloatToIntFunctionParams struct {
	Function *pb.BoolAndFloatToIntFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndFloatToIntFunctionParams(function *pb.BoolAndFloatToIntFunction, input, state string) BoolAndFloatToIntFunctionParams {
	return BoolAndFloatToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolAndFloatToFloatFunctionParams struct {
	Function *pb.BoolAndFloatToFloatFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndFloatToFloatFunctionParams(function *pb.BoolAndFloatToFloatFunction, input, state string) BoolAndFloatToFloatFunctionParams {
	return BoolAndFloatToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolAndFloatToStringFunctionParams struct {
	Function *pb.BoolAndFloatToStringFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndFloatToStringFunctionParams(function *pb.BoolAndFloatToStringFunction, input, state string) BoolAndFloatToStringFunctionParams {
	return BoolAndFloatToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolAndStringToBoolFunctionParams struct {
	Function *pb.BoolAndStringToBoolFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndStringToBoolFunctionParams(function *pb.BoolAndStringToBoolFunction, input, state string) BoolAndStringToBoolFunctionParams {
	return BoolAndStringToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolAndStringToIntFunctionParams struct {
	Function *pb.BoolAndStringToIntFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndStringToIntFunctionParams(function *pb.BoolAndStringToIntFunction, input, state string) BoolAndStringToIntFunctionParams {
	return BoolAndStringToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolAndStringToFloatFunctionParams struct {
	Function *pb.BoolAndStringToFloatFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndStringToFloatFunctionParams(function *pb.BoolAndStringToFloatFunction, input, state string) BoolAndStringToFloatFunctionParams {
	return BoolAndStringToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolAndStringToStringFunctionParams struct {
	Function *pb.BoolAndStringToStringFunction
	InputVariable string
	StateVariable string
}

func NewBoolAndStringToStringFunctionParams(function *pb.BoolAndStringToStringFunction, input, state string) BoolAndStringToStringFunctionParams {
	return BoolAndStringToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndBoolToBoolFunctionParams struct {
	Function *pb.IntAndBoolToBoolFunction
	InputVariable string
	StateVariable string
}

func NewIntAndBoolToBoolFunctionParams(function *pb.IntAndBoolToBoolFunction, input, state string) IntAndBoolToBoolFunctionParams {
	return IntAndBoolToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndBoolToIntFunctionParams struct {
	Function *pb.IntAndBoolToIntFunction
	InputVariable string
	StateVariable string
}

func NewIntAndBoolToIntFunctionParams(function *pb.IntAndBoolToIntFunction, input, state string) IntAndBoolToIntFunctionParams {
	return IntAndBoolToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndBoolToFloatFunctionParams struct {
	Function *pb.IntAndBoolToFloatFunction
	InputVariable string
	StateVariable string
}

func NewIntAndBoolToFloatFunctionParams(function *pb.IntAndBoolToFloatFunction, input, state string) IntAndBoolToFloatFunctionParams {
	return IntAndBoolToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndBoolToStringFunctionParams struct {
	Function *pb.IntAndBoolToStringFunction
	InputVariable string
	StateVariable string
}

func NewIntAndBoolToStringFunctionParams(function *pb.IntAndBoolToStringFunction, input, state string) IntAndBoolToStringFunctionParams {
	return IntAndBoolToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndIntToBoolFunctionParams struct {
	Function *pb.IntAndIntToBoolFunction
	InputVariable string
	StateVariable string
}

func NewIntAndIntToBoolFunctionParams(function *pb.IntAndIntToBoolFunction, input, state string) IntAndIntToBoolFunctionParams {
	return IntAndIntToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndIntToIntFunctionParams struct {
	Function *pb.IntAndIntToIntFunction
	InputVariable string
	StateVariable string
}

func NewIntAndIntToIntFunctionParams(function *pb.IntAndIntToIntFunction, input, state string) IntAndIntToIntFunctionParams {
	return IntAndIntToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndIntToFloatFunctionParams struct {
	Function *pb.IntAndIntToFloatFunction
	InputVariable string
	StateVariable string
}

func NewIntAndIntToFloatFunctionParams(function *pb.IntAndIntToFloatFunction, input, state string) IntAndIntToFloatFunctionParams {
	return IntAndIntToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndIntToStringFunctionParams struct {
	Function *pb.IntAndIntToStringFunction
	InputVariable string
	StateVariable string
}

func NewIntAndIntToStringFunctionParams(function *pb.IntAndIntToStringFunction, input, state string) IntAndIntToStringFunctionParams {
	return IntAndIntToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndFloatToBoolFunctionParams struct {
	Function *pb.IntAndFloatToBoolFunction
	InputVariable string
	StateVariable string
}

func NewIntAndFloatToBoolFunctionParams(function *pb.IntAndFloatToBoolFunction, input, state string) IntAndFloatToBoolFunctionParams {
	return IntAndFloatToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndFloatToIntFunctionParams struct {
	Function *pb.IntAndFloatToIntFunction
	InputVariable string
	StateVariable string
}

func NewIntAndFloatToIntFunctionParams(function *pb.IntAndFloatToIntFunction, input, state string) IntAndFloatToIntFunctionParams {
	return IntAndFloatToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndFloatToFloatFunctionParams struct {
	Function *pb.IntAndFloatToFloatFunction
	InputVariable string
	StateVariable string
}

func NewIntAndFloatToFloatFunctionParams(function *pb.IntAndFloatToFloatFunction, input, state string) IntAndFloatToFloatFunctionParams {
	return IntAndFloatToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndFloatToStringFunctionParams struct {
	Function *pb.IntAndFloatToStringFunction
	InputVariable string
	StateVariable string
}

func NewIntAndFloatToStringFunctionParams(function *pb.IntAndFloatToStringFunction, input, state string) IntAndFloatToStringFunctionParams {
	return IntAndFloatToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndStringToBoolFunctionParams struct {
	Function *pb.IntAndStringToBoolFunction
	InputVariable string
	StateVariable string
}

func NewIntAndStringToBoolFunctionParams(function *pb.IntAndStringToBoolFunction, input, state string) IntAndStringToBoolFunctionParams {
	return IntAndStringToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndStringToIntFunctionParams struct {
	Function *pb.IntAndStringToIntFunction
	InputVariable string
	StateVariable string
}

func NewIntAndStringToIntFunctionParams(function *pb.IntAndStringToIntFunction, input, state string) IntAndStringToIntFunctionParams {
	return IntAndStringToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndStringToFloatFunctionParams struct {
	Function *pb.IntAndStringToFloatFunction
	InputVariable string
	StateVariable string
}

func NewIntAndStringToFloatFunctionParams(function *pb.IntAndStringToFloatFunction, input, state string) IntAndStringToFloatFunctionParams {
	return IntAndStringToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntAndStringToStringFunctionParams struct {
	Function *pb.IntAndStringToStringFunction
	InputVariable string
	StateVariable string
}

func NewIntAndStringToStringFunctionParams(function *pb.IntAndStringToStringFunction, input, state string) IntAndStringToStringFunctionParams {
	return IntAndStringToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndBoolToBoolFunctionParams struct {
	Function *pb.FloatAndBoolToBoolFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndBoolToBoolFunctionParams(function *pb.FloatAndBoolToBoolFunction, input, state string) FloatAndBoolToBoolFunctionParams {
	return FloatAndBoolToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndBoolToIntFunctionParams struct {
	Function *pb.FloatAndBoolToIntFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndBoolToIntFunctionParams(function *pb.FloatAndBoolToIntFunction, input, state string) FloatAndBoolToIntFunctionParams {
	return FloatAndBoolToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndBoolToFloatFunctionParams struct {
	Function *pb.FloatAndBoolToFloatFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndBoolToFloatFunctionParams(function *pb.FloatAndBoolToFloatFunction, input, state string) FloatAndBoolToFloatFunctionParams {
	return FloatAndBoolToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndBoolToStringFunctionParams struct {
	Function *pb.FloatAndBoolToStringFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndBoolToStringFunctionParams(function *pb.FloatAndBoolToStringFunction, input, state string) FloatAndBoolToStringFunctionParams {
	return FloatAndBoolToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndIntToBoolFunctionParams struct {
	Function *pb.FloatAndIntToBoolFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndIntToBoolFunctionParams(function *pb.FloatAndIntToBoolFunction, input, state string) FloatAndIntToBoolFunctionParams {
	return FloatAndIntToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndIntToIntFunctionParams struct {
	Function *pb.FloatAndIntToIntFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndIntToIntFunctionParams(function *pb.FloatAndIntToIntFunction, input, state string) FloatAndIntToIntFunctionParams {
	return FloatAndIntToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndIntToFloatFunctionParams struct {
	Function *pb.FloatAndIntToFloatFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndIntToFloatFunctionParams(function *pb.FloatAndIntToFloatFunction, input, state string) FloatAndIntToFloatFunctionParams {
	return FloatAndIntToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndIntToStringFunctionParams struct {
	Function *pb.FloatAndIntToStringFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndIntToStringFunctionParams(function *pb.FloatAndIntToStringFunction, input, state string) FloatAndIntToStringFunctionParams {
	return FloatAndIntToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndFloatToBoolFunctionParams struct {
	Function *pb.FloatAndFloatToBoolFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndFloatToBoolFunctionParams(function *pb.FloatAndFloatToBoolFunction, input, state string) FloatAndFloatToBoolFunctionParams {
	return FloatAndFloatToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndFloatToIntFunctionParams struct {
	Function *pb.FloatAndFloatToIntFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndFloatToIntFunctionParams(function *pb.FloatAndFloatToIntFunction, input, state string) FloatAndFloatToIntFunctionParams {
	return FloatAndFloatToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndFloatToFloatFunctionParams struct {
	Function *pb.FloatAndFloatToFloatFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndFloatToFloatFunctionParams(function *pb.FloatAndFloatToFloatFunction, input, state string) FloatAndFloatToFloatFunctionParams {
	return FloatAndFloatToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndFloatToStringFunctionParams struct {
	Function *pb.FloatAndFloatToStringFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndFloatToStringFunctionParams(function *pb.FloatAndFloatToStringFunction, input, state string) FloatAndFloatToStringFunctionParams {
	return FloatAndFloatToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndStringToBoolFunctionParams struct {
	Function *pb.FloatAndStringToBoolFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndStringToBoolFunctionParams(function *pb.FloatAndStringToBoolFunction, input, state string) FloatAndStringToBoolFunctionParams {
	return FloatAndStringToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndStringToIntFunctionParams struct {
	Function *pb.FloatAndStringToIntFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndStringToIntFunctionParams(function *pb.FloatAndStringToIntFunction, input, state string) FloatAndStringToIntFunctionParams {
	return FloatAndStringToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndStringToFloatFunctionParams struct {
	Function *pb.FloatAndStringToFloatFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndStringToFloatFunctionParams(function *pb.FloatAndStringToFloatFunction, input, state string) FloatAndStringToFloatFunctionParams {
	return FloatAndStringToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatAndStringToStringFunctionParams struct {
	Function *pb.FloatAndStringToStringFunction
	InputVariable string
	StateVariable string
}

func NewFloatAndStringToStringFunctionParams(function *pb.FloatAndStringToStringFunction, input, state string) FloatAndStringToStringFunctionParams {
	return FloatAndStringToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndBoolToBoolFunctionParams struct {
	Function *pb.StringAndBoolToBoolFunction
	InputVariable string
	StateVariable string
}

func NewStringAndBoolToBoolFunctionParams(function *pb.StringAndBoolToBoolFunction, input, state string) StringAndBoolToBoolFunctionParams {
	return StringAndBoolToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndBoolToIntFunctionParams struct {
	Function *pb.StringAndBoolToIntFunction
	InputVariable string
	StateVariable string
}

func NewStringAndBoolToIntFunctionParams(function *pb.StringAndBoolToIntFunction, input, state string) StringAndBoolToIntFunctionParams {
	return StringAndBoolToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndBoolToFloatFunctionParams struct {
	Function *pb.StringAndBoolToFloatFunction
	InputVariable string
	StateVariable string
}

func NewStringAndBoolToFloatFunctionParams(function *pb.StringAndBoolToFloatFunction, input, state string) StringAndBoolToFloatFunctionParams {
	return StringAndBoolToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndBoolToStringFunctionParams struct {
	Function *pb.StringAndBoolToStringFunction
	InputVariable string
	StateVariable string
}

func NewStringAndBoolToStringFunctionParams(function *pb.StringAndBoolToStringFunction, input, state string) StringAndBoolToStringFunctionParams {
	return StringAndBoolToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndIntToBoolFunctionParams struct {
	Function *pb.StringAndIntToBoolFunction
	InputVariable string
	StateVariable string
}

func NewStringAndIntToBoolFunctionParams(function *pb.StringAndIntToBoolFunction, input, state string) StringAndIntToBoolFunctionParams {
	return StringAndIntToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndIntToIntFunctionParams struct {
	Function *pb.StringAndIntToIntFunction
	InputVariable string
	StateVariable string
}

func NewStringAndIntToIntFunctionParams(function *pb.StringAndIntToIntFunction, input, state string) StringAndIntToIntFunctionParams {
	return StringAndIntToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndIntToFloatFunctionParams struct {
	Function *pb.StringAndIntToFloatFunction
	InputVariable string
	StateVariable string
}

func NewStringAndIntToFloatFunctionParams(function *pb.StringAndIntToFloatFunction, input, state string) StringAndIntToFloatFunctionParams {
	return StringAndIntToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndIntToStringFunctionParams struct {
	Function *pb.StringAndIntToStringFunction
	InputVariable string
	StateVariable string
}

func NewStringAndIntToStringFunctionParams(function *pb.StringAndIntToStringFunction, input, state string) StringAndIntToStringFunctionParams {
	return StringAndIntToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndFloatToBoolFunctionParams struct {
	Function *pb.StringAndFloatToBoolFunction
	InputVariable string
	StateVariable string
}

func NewStringAndFloatToBoolFunctionParams(function *pb.StringAndFloatToBoolFunction, input, state string) StringAndFloatToBoolFunctionParams {
	return StringAndFloatToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndFloatToIntFunctionParams struct {
	Function *pb.StringAndFloatToIntFunction
	InputVariable string
	StateVariable string
}

func NewStringAndFloatToIntFunctionParams(function *pb.StringAndFloatToIntFunction, input, state string) StringAndFloatToIntFunctionParams {
	return StringAndFloatToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndFloatToFloatFunctionParams struct {
	Function *pb.StringAndFloatToFloatFunction
	InputVariable string
	StateVariable string
}

func NewStringAndFloatToFloatFunctionParams(function *pb.StringAndFloatToFloatFunction, input, state string) StringAndFloatToFloatFunctionParams {
	return StringAndFloatToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndFloatToStringFunctionParams struct {
	Function *pb.StringAndFloatToStringFunction
	InputVariable string
	StateVariable string
}

func NewStringAndFloatToStringFunctionParams(function *pb.StringAndFloatToStringFunction, input, state string) StringAndFloatToStringFunctionParams {
	return StringAndFloatToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndStringToBoolFunctionParams struct {
	Function *pb.StringAndStringToBoolFunction
	InputVariable string
	StateVariable string
}

func NewStringAndStringToBoolFunctionParams(function *pb.StringAndStringToBoolFunction, input, state string) StringAndStringToBoolFunctionParams {
	return StringAndStringToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndStringToIntFunctionParams struct {
	Function *pb.StringAndStringToIntFunction
	InputVariable string
	StateVariable string
}

func NewStringAndStringToIntFunctionParams(function *pb.StringAndStringToIntFunction, input, state string) StringAndStringToIntFunctionParams {
	return StringAndStringToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndStringToFloatFunctionParams struct {
	Function *pb.StringAndStringToFloatFunction
	InputVariable string
	StateVariable string
}

func NewStringAndStringToFloatFunctionParams(function *pb.StringAndStringToFloatFunction, input, state string) StringAndStringToFloatFunctionParams {
	return StringAndStringToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringAndStringToStringFunctionParams struct {
	Function *pb.StringAndStringToStringFunction
	InputVariable string
	StateVariable string
}

func NewStringAndStringToStringFunctionParams(function *pb.StringAndStringToStringFunction, input, state string) StringAndStringToStringFunctionParams {
	return StringAndStringToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

//
// ----- N-ary Functions -----
//

type BoolsToBoolFunctionParams struct {
	Function *pb.BoolsToBoolFunction
	InputVariable string
	StateVariable string
}

func NewBoolsToBoolFunctionParams(function *pb.BoolsToBoolFunction, input, state string) BoolsToBoolFunctionParams {
	return BoolsToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolsToIntFunctionParams struct {
	Function *pb.BoolsToIntFunction
	InputVariable string
	StateVariable string
}

func NewBoolsToIntFunctionParams(function *pb.BoolsToIntFunction, input, state string) BoolsToIntFunctionParams {
	return BoolsToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolsToFloatFunctionParams struct {
	Function *pb.BoolsToFloatFunction
	InputVariable string
	StateVariable string
}

func NewBoolsToFloatFunctionParams(function *pb.BoolsToFloatFunction, input, state string) BoolsToFloatFunctionParams {
	return BoolsToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type BoolsToStringFunctionParams struct {
	Function *pb.BoolsToStringFunction
	InputVariable string
	StateVariable string
}

func NewBoolsToStringFunctionParams(function *pb.BoolsToStringFunction, input, state string) BoolsToStringFunctionParams {
	return BoolsToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntsToBoolFunctionParams struct {
	Function *pb.IntsToBoolFunction
	InputVariable string
	StateVariable string
}

func NewIntsToBoolFunctionParams(function *pb.IntsToBoolFunction, input, state string) IntsToBoolFunctionParams {
	return IntsToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntsToIntFunctionParams struct {
	Function *pb.IntsToIntFunction
	InputVariable string
	StateVariable string
}

func NewIntsToIntFunctionParams(function *pb.IntsToIntFunction, input, state string) IntsToIntFunctionParams {
	return IntsToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntsToFloatFunctionParams struct {
	Function *pb.IntsToFloatFunction
	InputVariable string
	StateVariable string
}

func NewIntsToFloatFunctionParams(function *pb.IntsToFloatFunction, input, state string) IntsToFloatFunctionParams {
	return IntsToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntsToStringFunctionParams struct {
	Function *pb.IntsToStringFunction
	InputVariable string
	StateVariable string
}

func NewIntsToStringFunctionParams(function *pb.IntsToStringFunction, input, state string) IntsToStringFunctionParams {
	return IntsToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatsToBoolFunctionParams struct {
	Function *pb.FloatsToBoolFunction
	InputVariable string
	StateVariable string
}

func NewFloatsToBoolFunctionParams(function *pb.FloatsToBoolFunction, input, state string) FloatsToBoolFunctionParams {
	return FloatsToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatsToIntFunctionParams struct {
	Function *pb.FloatsToIntFunction
	InputVariable string
	StateVariable string
}

func NewFloatsToIntFunctionParams(function *pb.FloatsToIntFunction, input, state string) FloatsToIntFunctionParams {
	return FloatsToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatsToFloatFunctionParams struct {
	Function *pb.FloatsToFloatFunction
	InputVariable string
	StateVariable string
}

func NewFloatsToFloatFunctionParams(function *pb.FloatsToFloatFunction, input, state string) FloatsToFloatFunctionParams {
	return FloatsToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatsToStringFunctionParams struct {
	Function *pb.FloatsToStringFunction
	InputVariable string
	StateVariable string
}

func NewFloatsToStringFunctionParams(function *pb.FloatsToStringFunction, input, state string) FloatsToStringFunctionParams {
	return FloatsToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringsToBoolFunctionParams struct {
	Function *pb.StringsToBoolFunction
	InputVariable string
	StateVariable string
}

func NewStringsToBoolFunctionParams(function *pb.StringsToBoolFunction, input, state string) StringsToBoolFunctionParams {
	return StringsToBoolFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringsToIntFunctionParams struct {
	Function *pb.StringsToIntFunction
	InputVariable string
	StateVariable string
}

func NewStringsToIntFunctionParams(function *pb.StringsToIntFunction, input, state string) StringsToIntFunctionParams {
	return StringsToIntFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringsToFloatFunctionParams struct {
	Function *pb.StringsToFloatFunction
	InputVariable string
	StateVariable string
}

func NewStringsToFloatFunctionParams(function *pb.StringsToFloatFunction, input, state string) StringsToFloatFunctionParams {
	return StringsToFloatFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringsToStringFunctionParams struct {
	Function *pb.StringsToStringFunction
	InputVariable string
	StateVariable string
}

func NewStringsToStringFunctionParams(function *pb.StringsToStringFunction, input, state string) StringsToStringFunctionParams {
	return StringsToStringFunctionParams{
		Function: function,
		InputVariable: input,
		StateVariable: state,
	}
}

//
// ----- If-Else Control Structures -----
//

type BoolValueIfParams struct {
	If *pb.BoolValueIf
	InputVariable string
	StateVariable string
}

func NewBoolValueIfParams(v *pb.BoolValueIf, input, state string) BoolValueIfParams {
	return BoolValueIfParams{
		If: v,
		InputVariable: input,
		StateVariable: state,
	}
}

type IntValueIfParams struct {
	If *pb.IntValueIf
	InputVariable string
	StateVariable string
}

func NewIntValueIfParams(v *pb.IntValueIf, input, state string) IntValueIfParams {
	return IntValueIfParams{
		If: v,
		InputVariable: input,
		StateVariable: state,
	}
}

type FloatValueIfParams struct {
	If *pb.FloatValueIf
	InputVariable string
	StateVariable string
}

func NewFloatValueIfParams(v *pb.FloatValueIf, input, state string) FloatValueIfParams {
	return FloatValueIfParams{
		If: v,
		InputVariable: input,
		StateVariable: state,
	}
}

type StringValueIfParams struct {
	If *pb.StringValueIf
	InputVariable string
	StateVariable string
}

func NewStringValueIfParams(v *pb.StringValueIf, input, state string) StringValueIfParams {
	return StringValueIfParams{
		If: v,
		InputVariable: input,
		StateVariable: state,
	}
}

//
// ----- Others parameter constructors -----
//

type EffectParams struct {
	Effect *pb.Effect
	InputVariable string
	StateVariable string
}

func NewEffectParams(effect *pb.Effect, input, state string) EffectParams {
	return EffectParams {
		Effect: effect,
		InputVariable: input,
		StateVariable: state,
	}
}

type ResponseParams struct {
	Reference *pb.Reference
	InputVariable string
	StateVariable string
}

func NewResponseParams(reference *pb.Reference, input, state string) ResponseParams {
	return ResponseParams {
		Reference: reference,
		InputVariable: input,
		StateVariable: state,
	}
}

type MessageInitializerParams struct {
	Identifier string
	Package string
	MessageDescriptor *desc.MessageDescriptor
}

func NewMessageInitializerParams(ident, pkg string, msg *desc.MessageDescriptor) MessageInitializerParams {
	return MessageInitializerParams {
		Identifier: ident,
		Package: pkg,
		MessageDescriptor: msg,
	}
}

type MessageCopyParams struct {
	LeftHandIdentifier string
	RightHandIdentifier string
	Package string
	MessageDescriptor *desc.MessageDescriptor
}

func NewMessageCopyParams(left, right, pkg string, msg *desc.MessageDescriptor) MessageCopyParams {
	return MessageCopyParams {
		LeftHandIdentifier: left,
		RightHandIdentifier: right,
		Package: pkg,
		MessageDescriptor: msg,
	}
}

